# DNS Server Default Configuration
# This file contains sensible defaults for all configuration parameters

# Server Configuration
server:
  bind_address: "0.0.0.0"  # Bind to all interfaces for host networking
  dns_port: 9953  # Non-privileged port for development
  web_port: 9980
  workers: 4

  # Performance Optimization Settings
  max_concurrent_requests: 1000    # Maximum concurrent DNS requests
  request_queue_size: 5000         # Maximum request queue size for backpressure
  max_upstream_connections: 100    # Maximum upstream connection pool size
  connection_timeout: 30.0         # Connection timeout in seconds

# Upstream DNS Servers
# These servers will be used for forwarding queries when recursive resolution is needed
upstream_servers:
  - "8.8.8.8"        # Google DNS Primary
  - "1.1.1.1"        # Cloudflare DNS Primary
  - "208.67.222.222" # OpenDNS Primary

# Cache Configuration
cache:
  max_size_mb: 100     # Maximum cache size in megabytes
  default_ttl: 300     # Default TTL in seconds (5 minutes)
  min_ttl: 1           # Minimum TTL in seconds
  max_ttl: 86400       # Maximum TTL in seconds (24 hours)
  negative_ttl: 300    # TTL for negative cache entries (NXDOMAIN, etc.)

# Logging Configuration
logging:
  level: "INFO"                    # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  format: "json"                   # Log format (json, text)
  file: "logs/dns-server.log"      # Log file path
  max_size_mb: 50                  # Maximum log file size before rotation
  backup_count: 5                  # Number of backup log files to keep

# Security Configuration
security:
  rate_limit_per_ip: 100           # Maximum queries per IP per minute
  allowed_networks: ["0.0.0.0/0"]  # Allowed networks in CIDR notation
  blacklist_enabled: true          # Enable domain blacklisting
  debug_client_ip: false           # Enable detailed client IP debugging logs

# Web Interface Configuration
web:
  enabled: true              # Enable web interface
  real_time_updates: true    # Enable real-time updates via WebSocket
  history_limit: 1000        # Number of queries to keep in history

# DNS Resolution Configuration
resolution:
  query_timeout: 5           # Query timeout in seconds
  retry_attempts: 3          # Number of retry attempts for failed queries
  retry_interval: 1          # Interval between retries in seconds
  recursive_enabled: true    # Enable recursive resolution
  iterative_enabled: true    # Enable iterative resolution

# Performance Configuration
performance:
  max_concurrent_queries: 1000    # Maximum concurrent queries (deprecated - use server.max_concurrent_requests)
  connection_timeout: 30          # Connection timeout in seconds (deprecated - use server.connection_timeout)
  buffer_size: 8192              # Buffer size for network operations

  # Memory Management
  memory_monitoring_enabled: true  # Enable memory usage monitoring
  memory_warning_threshold_mb: 1000  # Memory usage warning threshold
  memory_cleanup_interval: 300    # Memory cleanup interval in seconds

  # Connection Pool Settings
  connection_pool_enabled: true   # Enable connection pooling
  connection_pool_cleanup_interval: 60  # Cleanup interval for old connections

# Monitoring Configuration
monitoring:
  health_check_enabled: true      # Enable health check endpoint
  metrics_enabled: true           # Enable Prometheus metrics
  alerts_enabled: false           # Enable alerting (requires configuration)

  # Performance Monitoring
  performance_monitoring_enabled: true  # Enable detailed performance monitoring
  performance_monitoring_interval: 5.0  # Monitoring collection interval in seconds
  performance_history_size: 1000        # Number of performance samples to keep

# Time Configuration
time:
  proactive_refresh_enabled: true # Enable proactive cache refresh
  refresh_threshold: 0.8          # Refresh when TTL reaches 80% of expiration
