# DNS Server Configuration File
# This file contains the configuration for the DNS server
# All settings are optional and will use sensible defaults if not specified

# Server Configuration
server:
  bind_address: "0.0.0.0"  # Bind to all interfaces
  dns_port: 53             # Container internal DNS port (exposed as 9953)
  web_port: 80             # Container internal web port (exposed as 9980)
  workers: 4

  # Performance Optimization Settings
  max_concurrent_requests: 1000    # Maximum concurrent DNS requests
  request_queue_size: 5000         # Maximum request queue size for backpressure
  max_upstream_connections: 100    # Maximum upstream connection pool size
  connection_timeout: 30.0         # Connection timeout in seconds

# Upstream DNS Servers
upstream_servers:
  - "8.8.8.8"           # Google DNS
  - "8.8.4.4"           # Google DNS
  - "1.1.1.1"           # Cloudflare DNS
  - "1.0.0.1"           # Cloudflare DNS

# Security Configuration
security:
  rate_limit_per_ip: 100               # Max queries per IP per minute
  block_malformed_requests: true       # Block malformed DNS requests
  enable_dns_sec: false               # Enable DNSSEC validation (experimental)
  enable_query_logging: true          # Log all DNS queries
  max_query_length: 512               # Maximum query length in bytes
  enable_response_filtering: false    # Enable response filtering
  debug_client_ip: false              # Debug client IP extraction

# Logging Configuration  
logging:
  level: "INFO"                       # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "structured"                # Log format: simple, detailed, structured
  file: "logs/app.log"                # General application log file
  max_size_mb: 100                    # Maximum log file size in MB
  backup_count: 5                     # Number of backup log files
  enable_request_logging: true        # Log all requests
  log_query_details: true             # Log detailed query information
  log_performance_metrics: true       # Log performance metrics
  log_security_events: true           # Log security events
  structured_format: "json"           # Structured log format: json, key_value

# Monitoring Configuration
monitoring:
  enable_metrics: true                # Enable metrics collection
  metrics_port: 9090                  # Port for metrics endpoint
  enable_health_check: true           # Enable health check endpoint
  health_check_interval: 30           # Health check interval in seconds
  performance_tracking: true          # Track performance metrics
  alert_on_high_error_rate: true      # Alert on high error rates
  error_rate_threshold: 0.1           # Error rate threshold (0.0-1.0)
  alert_on_slow_queries: true         # Alert on slow queries
  slow_query_threshold_ms: 1000.0     # Slow query threshold in milliseconds

# Web Interface Configuration
web:
  enabled: true                       # Enable web interface
  debug: false                        # Enable debug mode
  cors_enabled: true                  # Enable CORS
  cors_origins: ["*"]                 # CORS allowed origins
  static_files_path: "web"            # Path to static files
  api_rate_limit: 1000                # API rate limit per hour
  websocket_enabled: true             # Enable WebSocket connections
  websocket_max_connections: 100      # Maximum WebSocket connections
